image:
  home: /image/journal/

logging:
  level:
    club.geek66.downloader: warn


spring:
  datasource:
    url: jdbc:h2:file:~/h2/image;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 32 # default: 10

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: false
          use_sql_comments: true
          format_sql: true

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true

server:
  port: 80